name: arch-test

on:
  push:
    branches:
      - "*"
  pull_request:
    branches:
      - "*"

jobs:
  build-hl1d:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build episodic
      env:
        DISCORD_TOKEN: ${{ secrets.DISCORD_TOKEN }}
        SSH_PASS: ${{ secrets.SSH_PASS }}
      run: |
        mkdir $HOME/.android
        sudo apt-get update
        sudo apt install -y make unzip python3 ccache imagemagick
        wget https://dl.google.com/android/repository/android-ndk-r10e-linux-x86_64.zip -o /dev/null
        unzip android-ndk-r10e-linux-x86_64.zip > /dev/null
        wget https://github.com/llvm/llvm-project/releases/download/llvmorg-11.1.0/clang+llvm-11.1.0-x86_64-linux-gnu-ubuntu-16.04.tar.xz -o /dev/null
        tar xvf clang+llvm-11.1.0-x86_64-linux-gnu-ubuntu-16.04.tar.xz > /dev/null
        mv clang+llvm-11.1.0-x86_64-linux-gnu-ubuntu-16.04 clang/
        export PATH=$(pwd)/clang/bin:$PATH
        
        mv android-ndk-r10e ndk/
        export ANDROID_NDK_HOME=$(pwd)/ndk
        
        git clone --depth 1 https://github.com/nillerusr/source-engine/ --recursive
        #fix
        cd source-engine
        mkdir lib
        ./waf configure -T release --android=x86,host,21 -8 --prefix=android/ --togles --build-game=hl1 --use-ccache --disable-warns || (cat build/config.log;exit)
        ./waf install --target=client,server --destdir=lib || exit
        #
        mkdir library
        rm -rf android/
        find lib -name "*.so" -exec mv -t ./library {} +
    - uses: actions/upload-artifact@v3
      with:
        name: hls x86
        path: ./library
        if-no-files-found: error
        
  build-hl1:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build hl1
      env:
        DISCORD_TOKEN: ${{ secrets.DISCORD_TOKEN }}
        SSH_PASS: ${{ secrets.SSH_PASS }}
      run: |
        mkdir $HOME/.android
        sudo apt-get update
        sudo apt install -y make unzip python3 ccache imagemagick
        wget https://dl.google.com/android/repository/android-ndk-r10e-linux-x86_64.zip -o /dev/null
        unzip android-ndk-r10e-linux-x86_64.zip > /dev/null
        wget https://github.com/llvm/llvm-project/releases/download/llvmorg-11.1.0/clang+llvm-11.1.0-x86_64-linux-gnu-ubuntu-16.04.tar.xz -o /dev/null
        tar xvf clang+llvm-11.1.0-x86_64-linux-gnu-ubuntu-16.04.tar.xz > /dev/null
        mv clang+llvm-11.1.0-x86_64-linux-gnu-ubuntu-16.04 clang/
        export PATH=$(pwd)/clang/bin:$PATH
        
        mv android-ndk-r10e ndk/
        export ANDROID_NDK_HOME=$(pwd)/ndk
        
        git clone --depth 1 https://github.com/nillerusr/source-engine/ --recursive
        mkdir -p libs/ apks/
        cd source-engine
        ./waf configure -T release --android=aarch64,host,21 -8 --prefix=android/ --togles --build-game=hl1 --use-ccache --disable-warns || (cat build/config.log;exit)
        ./waf install --target=client,server || exit
        mkdir -p ../libs/hl1
        cp android/lib/arm64-v8a/libserver.so ../libs/hl1/
        cp android/lib/arm64-v8a/libclient.so ../libs/hl1/
        rm -rf android/
        find ./libs -name "*.so" -exec mv -t ./build1 {} +
    - uses: actions/upload-artifact@v3
      with:
        name: hls
        path: ./libs
        if-no-files-found: error
