name: arch-test

on:
  push:
    branches:
      - "*"
  pull_request:
    branches:
      - "*"

jobs:
  build-episodic:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build episodic
      env:
        DISCORD_TOKEN: ${{ secrets.DISCORD_TOKEN }}
        SSH_PASS: ${{ secrets.SSH_PASS }}
      run: |
        sudo chmod +777 hls.sh
        ./hls.sh
        mkdir apk
        find ./build -name "*.apk" -exec mv -t ./build1 {} +
    - uses: actions/upload-artifact@v3
      with:
        name: ep1 ep2
        path: ./apk
        if-no-files-found: error
        
  build-hl1:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build hl1
      env:
        DISCORD_TOKEN: ${{ secrets.DISCORD_TOKEN }}
        SSH_PASS: ${{ secrets.SSH_PASS }}
      run: |
        sudo chmod +777 hls-x86_64.sh
        ./hls-x86_64.sh
        mkdir apk
        find ./build -name "*.apk" -exec mv -t ./build1 {} +
    - uses: actions/upload-artifact@v3
      with:
        name: hls
        path: ./apk
        if-no-files-found: error
